name: Test
on: 
  push:
    branches:
      - main
      - feature/*
env: # Or as an environment variable
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install coverage-badge
          pip install numpy
          pip install .
      - name: Test with unittest
        run: | 
          coverage run --source=src -m unittest test/test*.py
      - name: Upload coverage reports to Codecov
        run: | 
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t $CODECOV_TOKEN
